# Generated by Django 5.2.4 on 2025-07-19 13:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=500)),
                ('bio_summary', models.CharField(max_length=500)),
                ('bio', models.TextField(max_length=5000)),
                ('profile_image', models.ImageField(blank=True, default='profiles/default-user.png', null=True, upload_to='profiles/')),
                ('social_github', models.CharField(blank=True, max_length=500, null=True)),
                ('social_linkedin', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
