# Generated by Django 5.2.4 on 2025-07-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_skill_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
