# Generated by Django 5.2.4 on 2025-07-20 06:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('project_image', models.ImageField(blank=True, default='projects/default-project.jpg', null=True, upload_to='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('description_summary', models.TextField(max_length=1000)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
