# Generated by Django 5.2.4 on 2025-07-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='news',
        ),
        migrations.RemoveField(
            model_name='link',
            name='news',
        ),
        migrations.RemoveField(
            model_name='video',
            name='news',
        ),
        migrations.AddField(
            model_name='news',
            name='images',
            field=models.ManyToManyField(to='news.image'),
        ),
        migrations.AddField(
            model_name='news',
            name='links',
            field=models.ManyToManyField(to='news.link'),
        ),
        migrations.AddField(
            model_name='news',
            name='videos',
            field=models.ManyToManyField(to='news.video'),
        ),
    ]
