# Generated by Django 5.2.4 on 2025-07-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_category_key_alter_category_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='summery',
        ),
        migrations.AddField(
            model_name='news',
            name='summary',
            field=models.TextField(max_length=1500, null=True),
        ),
    ]
