# Generated by Django 5.2.4 on 2025-07-20 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_productcategory_alter_project_tags_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
